table by_category

	column Reason_Category
		dataType: string
		summarizeBy: none
		sourceColumn: Reason_Category

	column denied_amt
		dataType: double
		summarizeBy: sum
		sourceColumn: denied_amt

	column denials
		dataType: int64
		summarizeBy: sum
		sourceColumn: denials

	measure 'Denied amount (by_category)' = SUM ( 'by_category'[denied_amt] )
		formatString: #,0.00
		displayFolder: Measures
		/// Denied amount for the 'Denied dollars by category' visual.

	partition by_category = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\by_category.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Reason_Category", type text},
				        {"denied_amt", type number},
				        {"denials", Int64.Type}
				    })
				in
				    Typed
