table submit_lag

	column band
		dataType: string
		summarizeBy: none
		sourceColumn: band

	column claims
		dataType: int64
		summarizeBy: sum
		sourceColumn: claims

	column denial_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: denial_pct

	measure 'Denial rate % (submit_lag)' = AVERAGE ( 'submit_lag'[denial_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// Denial rate % for the 'Submission lag and denial rate' visual.

	partition submit_lag = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\submit_lag.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"band", type text},
				        {"claims", Int64.Type},
				        {"denial_pct", type number}
				    })
				in
				    Typed
